# Generated by Django 4.1.5 on 2023-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
