# Generated by Django 4.1.5 on 2023-02-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_categorie_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categorie',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.categorie'),
        ),
    ]
