# Generated by Django 4.1.5 on 2023-02-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categorie',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='courses.categorie'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
