# Generated by Django 4.1.5 on 2023-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_categorie_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
