# Generated by Django 4.1.5 on 2023-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categorie',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='courses.categorie'),
        ),
    ]
